# Hand-written stub for the compiled _core extension. Keep in sync with
# src/cpp/slodl/bindings/.

from collections.abc import Sequence

import numpy as np
import numpy.typing as npt

class Node:
    @property
    def name(self) -> str: ...
    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __radd__(self, other: float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __rmul__(self, other: float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __rsub__(self, other: float) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...
    def __rtruediv__(self, other: float) -> Tensor: ...
    def sum(self) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def expand(self, shape: Sequence[int]) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def transpose(self, dim0: int = 0, dim1: int = 1) -> Tensor: ...
    @property
    def T(self) -> Tensor: ...
    requires_grad: bool
    def requires_grad_(self, flag: bool = True) -> None: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def grad(self) -> Tensor | None: ...
    @property
    def grad_fn(self) -> Node | None: ...
    def detach(self) -> Tensor: ...
    def backward(self) -> None: ...
    def __repr__(self) -> str: ...

class Tensor:
    @staticmethod
    def from_numpy(array: npt.NDArray[np.float64]) -> Tensor: ...
    def __init__(
        self,
        dims: Sequence[int],
        /,
        *args: float | Sequence[float],
    ) -> None: ...
    @property
    def shape(self) -> list[int]: ...
    def clone(self) -> Tensor: ...
    def item(self) -> float: ...
    def __len__(self) -> int: ...
    # A scalar element comes back as a float; anything else as a view.
    def __getitem__(self, index: int) -> Tensor | float: ...
    def __setitem__(self, index: int, value: float | Tensor) -> None: ...
    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __radd__(self, other: float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __rmul__(self, other: float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __rsub__(self, other: float) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...
    def __rtruediv__(self, other: float) -> Tensor: ...
    def sum(self) -> Tensor: ...
    def mean(self) -> Tensor: ...
    def expand(self, shape: Sequence[int]) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def transpose(self, dim0: int = 0, dim1: int = 1) -> Tensor: ...
    @property
    def T(self) -> Tensor: ...
    requires_grad: bool
    def requires_grad_(self, flag: bool = True) -> None: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def grad(self) -> Tensor | None: ...
    @property
    def grad_fn(self) -> Node | None: ...
    def detach(self) -> Tensor: ...
    def backward(self) -> None: ...
    def __repr__(self) -> str: ...

def add(a: Tensor, b: Tensor) -> Tensor: ...
def mul(a: Tensor, b: Tensor) -> Tensor: ...
def sub(a: Tensor, b: Tensor) -> Tensor: ...
def neg(a: Tensor) -> Tensor: ...
def div(a: Tensor, b: Tensor) -> Tensor: ...
def sum(a: Tensor) -> Tensor: ...
def mean(a: Tensor) -> Tensor: ...
def matmul(a: Tensor, b: Tensor) -> Tensor: ...
def transpose(a: Tensor, dim0: int = 0, dim1: int = 1) -> Tensor: ...
def expand(a: Tensor, shape: Sequence[int]) -> Tensor: ...
def is_grad_enabled() -> bool: ...
def set_grad_enabled(enabled: bool) -> None: ...
