# Hand-written stub for the compiled _core extension. Keep in sync with
# src/cpp/slodl/bindings/.

from collections.abc import Sequence

class Tensor:
    def __init__(
        self,
        dims: Sequence[int],
        /,
        *args: float | Sequence[float],
    ) -> None: ...
    @property
    def shape(self) -> list[int]: ...
    def item(self) -> float: ...
    def __len__(self) -> int: ...
    # A scalar element comes back as a float; anything else as a view.
    def __getitem__(self, index: int) -> Tensor | float: ...
    def __setitem__(self, index: int, value: float | Tensor) -> None: ...
    def __repr__(self) -> str: ...
